management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

journey:
  file: /var/journey/data.log


spring:
  redis:
    host: redis
    port: 6379
    lettuce:
      pool:
        min-idle: 10
        max-active: 20